# if something shouldn't ever be fodder, it's excluded
from sc2.ids.unit_typeid import UnitTypeId

FODDER_VALUES: dict[UnitTypeId, int] = {
    # zerg
    UnitTypeId.BROODLING: 0,
    UnitTypeId.CORRUPTOR: 7,
    UnitTypeId.DRONE: 2,
    UnitTypeId.HYDRALISK: 6,
    UnitTypeId.LOCUSTMP: 0,
    UnitTypeId.QUEEN: 1,
    UnitTypeId.ROACH: 4,
    UnitTypeId.ULTRALISK: 3,
    UnitTypeId.ZERGLING: 5,
    # shouldn't be fodder, but need values to recognise non fodder
    UnitTypeId.BANELING: 20,
    UnitTypeId.BROODLORD: 20,
    UnitTypeId.INFESTOR: 20,
    UnitTypeId.INFESTORBURROWED: 20,
    UnitTypeId.LURKERMP: 20,
    UnitTypeId.LURKERMPBURROWED: 20,
    UnitTypeId.MUTALISK: 20,
    UnitTypeId.RAVAGER: 20,
    UnitTypeId.SWARMHOSTMP: 20,
    UnitTypeId.SWARMHOSTBURROWEDMP: 20,
    UnitTypeId.VIPER: 20,
    # terran
    UnitTypeId.BATTLECRUISER: 11,
    UnitTypeId.CYCLONE: 6,
    UnitTypeId.HELLION: 5,
    UnitTypeId.HELLIONTANK: 2,
    UnitTypeId.MARAUDER: 1,
    UnitTypeId.MARINE: 4,
    UnitTypeId.REAPER: 7,
    UnitTypeId.THORAP: 3,
    UnitTypeId.SCV: 0,
    UnitTypeId.SIEGETANK: 8,
    UnitTypeId.VIKINGASSAULT: 10,
    UnitTypeId.VIKINGFIGHTER: 9,
    # shouldn't be fodder, but need values to recognise non fodder
    UnitTypeId.BANSHEE: 20,
    UnitTypeId.GHOST: 20,
    UnitTypeId.LIBERATOR: 20,
    UnitTypeId.LIBERATORAG: 20,
    UnitTypeId.MEDIVAC: 20,
    UnitTypeId.RAVEN: 20,
    UnitTypeId.SIEGETANKSIEGED: 20,
    UnitTypeId.WIDOWMINE: 20,
    UnitTypeId.WIDOWMINEBURROWED: 20,
    # protoss
    UnitTypeId.ADEPT: 4,
    UnitTypeId.ARCHON: 3,
    UnitTypeId.COLOSSUS: 7,
    UnitTypeId.DARKTEMPLAR: 6,
    UnitTypeId.DISRUPTOR: 8,
    UnitTypeId.IMMORTAL: 1,
    UnitTypeId.MOTHERSHIP: 9,
    UnitTypeId.PHOENIX: 11,
    UnitTypeId.PROBE: 0,
    UnitTypeId.STALKER: 5,
    UnitTypeId.VOIDRAY: 10,
    UnitTypeId.ZEALOT: 2,
    UnitTypeId.CARRIER: 20,
    UnitTypeId.HIGHTEMPLAR: 20,
    UnitTypeId.OBSERVER: 20,
    UnitTypeId.OBSERVERSIEGEMODE: 20,
    UnitTypeId.ORACLE: 20,
    UnitTypeId.SENTRY: 20,
    UnitTypeId.TEMPEST: 20,
    UnitTypeId.WARPPRISM: 20,
    UnitTypeId.WARPPRISMPHASING: 20,
}
